{
  "openapi": "3.0.0",
  "info": {
    "title": "API Clients",
    "description": "This is an API to handle clients",
    "version": "1.0.0",
    "contact": {
      "email": "contato.caioweliton@gmail.com"
    }
  },
  "paths": {
    "/cities": {
      "post": {
        "tags": ["City"],
        "summary": "Create city",
        "description": "Create a new city",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/definitions/CityRequestBody"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/definitions/CityResponseBody"
                }
              }
            }
          },
          "409": {
            "description": "Conflict",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "City already exists"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/definitions/InternalError"
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["City"],
        "summary": "List cities",
        "description": "List paginated cities with or without filters",
        "parameters": [
          {
            "name": "name",
            "in": "query",
            "description": "Part of the city name",
            "required": false,
            "schema": { "type": "string" }
          },
          {
            "name": "state",
            "in": "query",
            "description": "Part of the state name",
            "required": false,
            "schema": { "type": "string" }
          },
          {
            "name": "skip",
            "in": "query",
            "description": "Number of records to be skipped",
            "required": false,
            "schema": { "type": "string" }
          },
          {
            "name": "take",
            "in": "query",
            "description": "Number of records to be taken",
            "required": false,
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "cities": {
                      "type": "array",
                      "items": {
                        "$ref": "#/definitions/CityResponseBody"
                      }
                    },
                    "pagination": {
                      "$ref": "#/definitions/Pagination"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/definitions/InternalError"
                }
              }
            }
          }
        }
      }
    },
    "/clients": {
      "post": {
        "tags": ["Client"],
        "summary": "Create client",
        "description": "Create a new client",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/definitions/ClientRequestBody"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/definitions/ClientResponseBody1"
                }
              }
            }
          },
          "422": {
            "description": "Validation error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Unprocessable entity error"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/definitions/InternalError"
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Client"],
        "summary": "List clients",
        "description": "List paginated clients with or without filters",
        "parameters": [
          {
            "name": "full_name",
            "in": "query",
            "description": "Part of the client name",
            "required": false,
            "schema": { "type": "string" }
          },
          {
            "name": "skip",
            "in": "query",
            "description": "Number of records to be skipped",
            "required": false,
            "schema": { "type": "string" }
          },
          {
            "name": "take",
            "in": "query",
            "description": "Number of records to be taken",
            "required": false,
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "clients": {
                      "type": "array",
                      "items": {
                        "$ref": "#/definitions/ClientResponseBody2"
                      }
                    },
                    "pagination": {
                      "$ref": "#/definitions/Pagination"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/definitions/InternalError"
                }
              }
            }
          }
        }
      }
    },
    "/clients/{id}": {
      "get": {
        "tags": ["Client"],
        "summary": "Get client",
        "description": "Get client by id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Client id",
            "required": true,
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/definitions/ClientResponseBody2"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/definitions/InvalidIdError"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/definitions/ClientNotFound"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/definitions/InternalError"
                }
              }
            }
          }
        }
      },
      "patch": {
        "tags": ["Client"],
        "summary": "Update client name",
        "description": "Update a client name by id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Client id",
            "required": true,
            "schema": { "type": "string" }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/definitions/ClientUpdateNameRequestBody"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/definitions/ClientResponseBody1"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/definitions/InvalidIdError"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/definitions/ClientNotFound"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/definitions/InternalError"
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CityRequestBody": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "state": {
          "type": "string"
        }
      },
      "example": {
        "name": "any_city",
        "state": "any_state"
      }
    },
    "CityResponseBody": {
      "type": "object",
      "properties": {
        "id": {
          "type": "uuid"
        },
        "name": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "created_at": {
          "type": "date"
        }
      },
      "example": {
        "id": "dd60f3a6-2453-4961-8ca7-3bca56822118",
        "name": "any_city",
        "state": "any_state",
        "created_at": "2021-12-28T12:25:23.521Z"
      }
    },
    "InternalError": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      },
      "example": {
        "status": "error",
        "message": "Internal server error - some error"
      }
    },
    "Pagination": {
      "type": "object",
      "properties": {
        "skip": {
          "type": "number"
        },
        "take": {
          "type": "number"
        }
      },
      "example": {
        "skip": 0,
        "take": 10
      }
    },
    "ClientRequestBody": {
      "type": "object",
      "properties": {
        "full_name": {
          "type": "string"
        },
        "gender": {
          "type": "string"
        },
        "birth_date": {
          "type": "date"
        },
        "city_id": {
          "type": "uuid"
        }
      },
      "example": {
        "full_name": "John Doe",
        "gender": "M",
        "birth_date": "1970-01-01",
        "city_id": "d2b6966d-135e-4c41-9a91-5192803ad9ff"
      }
    },
    "ClientResponseBody1": {
      "type": "object",
      "properties": {
        "id": {
          "type": "uuid"
        },
        "full_name": {
          "type": "string"
        },
        "gender": {
          "type": "string"
        },
        "birth_date": {
          "type": "date"
        },
        "city_id": {
          "type": "uuid"
        },
        "created_at": {
          "type": "date"
        }
      },
      "example": {
        "id": "459280e8-340a-4354-b919-068941944284",
        "full_name": "John Doe",
        "gender": "M",
        "birth_date": "1970-01-01",
        "city_id": "d2b6966d-135e-4c41-9a91-5192803ad9ff",
        "created_at": "2021-12-28T11:54:40.963Z"
      }
    },
    "ClientResponseBody2": {
      "type": "object",
      "properties": {
        "id": {
          "type": "uuid"
        },
        "full_name": {
          "type": "string"
        },
        "gender": {
          "type": "string"
        },
        "birth_date": {
          "type": "date"
        },
        "age": {
          "type": "number"
        },
        "city_id": {
          "type": "uuid"
        },
        "city": {
          "$ref": "#/definitions/CityResponseBody"
        },
        "created_at": {
          "type": "date"
        }
      },
      "example": {
        "id": "459280e8-340a-4354-b919-068941944284",
        "full_name": "John Doe",
        "gender": "M",
        "birth_date": "1970-02-01",
        "age": 51,
        "city_id": "d2b6966d-135e-4c41-9a91-5192803ad9ff",
        "city": {
          "id": "d2b6966d-135e-4c41-9a91-5192803ad9ff",
          "name": "any_name",
          "state": "any_state",
          "created_at": "2021-12-27T12:44:33.298Z"
        },
        "created_at": "2021-12-28T11:54:40.963Z"
      }
    },
    "InvalidIdError": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      },
      "example": {
        "message": "Invalid id"
      }
    },
    "ClientNotFound": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      },
      "example": {
        "message": "Client not found"
      }
    },
    "ClientUpdateNameRequestBody": {
      "type": "object",
      "properties": {
        "full_name": {
          "type": "string"
        }
      },
      "example": {
        "full_name": "John Doe Updated"
      }
    }
  }
}
